### PR TITLE
Remove WindowsProfile parameters

### PR DESCRIPTION
**Pull request by cmurphy**
Windows node pools will be disabled from Rancher, so we should not
expose the settings to configure them.

https://github.com/rancher/rancher/issues/32586

### CODE REVIEW

**Review by cbron — APPROVED** [review]
lgtm, but lets wait to merge until we understand registration case

**Review by mjura — APPROVED** [review]
LGTM

**Comment by cmurphy** [comment]
Removed the windows example CR too

**Review by cbron — APPROVED** [review]

**Review by mjura — APPROVED** [review]
LGTM

**Review by thedadams — APPROVED** [review]

**Pull request merged**
